[tool.poetry]
name = "sip-demo-backend"
version = "0.1.0"
description = "Backend for AI-powered wine pairing app"
authors = ["aaron.feingold <ajfeingold88@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.8"
uvicorn = "^0.34.0"
asyncpg = "^0.30.0"
sqlalchemy = "^2.0.37"
psycopg2 = "^2.9.10"
pgvector = "^0.3.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
